-- liquibase formatted sql

-- changeset ycovich:1712840063611-1
CREATE TABLE attachments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    blob      BYTEA,
    ticket_id INTEGER,
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-2
CREATE TABLE categories
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-3
CREATE TABLE comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   INTEGER,
    text      VARCHAR(255),
    date      TIMESTAMP WITHOUT TIME ZONE,
    ticket_id INTEGER,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-4
CREATE TABLE feedbacks
(
    id        INTEGER NOT NULL,
    user_id   INTEGER,
    rate      SMALLINT,
    date      date,
    text      VARCHAR(255),
    ticket_id INTEGER,
    CONSTRAINT pk_feedbacks PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-5
CREATE TABLE histories
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id   INTEGER,
    date        TIMESTAMP WITHOUT TIME ZONE,
    action      VARCHAR(255),
    user_id     INTEGER,
    description VARCHAR(255),
    CONSTRAINT pk_histories PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-6
CREATE TABLE refresh_tokens
(
    id         UUID NOT NULL,
    user_id    INTEGER,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-7
CREATE TABLE tickets
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255),
    description             VARCHAR(255),
    created_on              date,
    desired_resolution_date date,
    state_id                SMALLINT,
    urgency_id              SMALLINT,
    assignee_id             INTEGER,
    owner_id                INTEGER,
    approver_id             INTEGER,
    category_id             INTEGER,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-8
CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    user_role  SMALLINT,
    password   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset ycovich:1712840063611-9
ALTER TABLE feedbacks
    ADD CONSTRAINT uc_feedbacks_ticket UNIQUE (ticket_id);

-- changeset ycovich:1712840063611-10
ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

-- changeset ycovich:1712840063611-11
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset ycovich:1712840063611-12
ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

-- changeset ycovich:1712840063611-13
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

-- changeset ycovich:1712840063611-14
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset ycovich:1712840063611-15
ALTER TABLE feedbacks
    ADD CONSTRAINT FK_FEEDBACKS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

-- changeset ycovich:1712840063611-16
ALTER TABLE feedbacks
    ADD CONSTRAINT FK_FEEDBACKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset ycovich:1712840063611-17
ALTER TABLE histories
    ADD CONSTRAINT FK_HISTORIES_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

-- changeset ycovich:1712840063611-18
ALTER TABLE histories
    ADD CONSTRAINT FK_HISTORIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset ycovich:1712840063611-19
ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_APPROVER FOREIGN KEY (approver_id) REFERENCES users (id);

-- changeset ycovich:1712840063611-20
ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES users (id);

-- changeset ycovich:1712840063611-21
ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

-- changeset ycovich:1712840063611-22
ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

