-- liquibase formatted sql

-- changeset ycovich:1711389725067-5
ALTER TABLE IF EXISTS attachment
    DROP CONSTRAINT fk_attachments_on_ticket;

-- changeset ycovich:1711389725067-1
CREATE TABLE IF NOT EXISTS attachments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    blob      BYTEA,
    ticket_id INTEGER,
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

-- changeset ycovich:1711389725067-2
CREATE TABLE tokens
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token   VARCHAR(255),
    type    VARCHAR(255),
    expired BOOLEAN,
    revoked BOOLEAN,
    user_id INTEGER,
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

-- changeset ycovich:1711389725067-3
ALTER TABLE attachments
    ADD CONSTRAINT fk_attachments_on_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE;

-- changeset ycovich:1711389725067-4
ALTER TABLE tokens
    ADD CONSTRAINT fk_tokens_on_user FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset ycovich:1711389725067-6
DROP TABLE IF EXISTS attachment CASCADE;

